---
- name: Deploy Apache Web Server Container
  hosts: webservers
  become: true

  tasks:
    - name: Copy project files to remote
      copy:
        src: ../site/
        dest: /home/parth/site/
        mode: '0755'

    - name: Copy deploy script to remote
      copy:
        src: ../scripts/deploy.sh
        dest: /home/parth/deploy.sh
        mode: '0755'

    - name: Run the deploy script on remote
      shell: bash /home/parth/deploy.sh
