---
- name: Deploy Apache Web Server Container
  hosts: webservers
  become: true

  tasks:
  - name: Copy deploy script to remote
    copy:
      src: "{{ playbook_dir }}/../scripts/deploy.sh"
      dest: /home/vboxuser/deploy.sh
      mode: '0755'

  - name: Run the deploy script on remote
    shell: bash /home/xboxuser/deploy.sh
